export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// profile actions
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

//auth actions
export const LOGOUT = 'LOGOUT';
export const USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE';
export const SET_MFA_STATUS = 'SET_MFA_STATUS';
export const SHOW_EMAIL_VERIFICATION = 'SHOW_EMAIL_VERIFICATION';
export const SET_RESET_PASSWORD_EMAIL = 'SET_RESET_PASSWORD_EMAIL';
export const USER_ALREADY_EXIST = 'USER_ALREADY_EXIST';
export const RESEND_EMAIL_STATUS = 'RESEND_EMAIL_STATUS';

//
export const GET_ALL_API_SECRET_KEY = 'GET_ALL_API_SECRET_KEY';

//balance actions

//deposit actions
export const ALL_DEPOSIT_BTC = 'ALL_DEPOSIT_BTC';
export const ALL_DEPOSIT_USDT = 'ALL_DEPOSIT_USDT';
export const GET_ADDRESS_BTC = 'GET_ADDRESS_BTC';
export const GET_ADDRESS_USDT = 'GET_ADDRESS_USDT';
export const GET_ADDRESS_BTC_STATUS = 'GET_ADDRESS_BTC_STATUS';
export const GET_ADDRESS_USDT_STATUS = 'GET_ADDRESS_USDT_STATUS';
export const DEPOSIT_FETCH_STATUS = 'DEPOSIT_FETCH_STATUS';

//withdraw actions
export const ALL_WITHDRAW_BTC = 'ALL_WITHDRAW_BTC';
export const ALL_WITHDRAW_USDT = 'ALL_WITHDRAW_USDT';
export const WITHDRAW_FETCH_STATUS = 'WITHDRAW_FETCH_STATUS';
